header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: Apache Software Foundation

  paths:
    - '**'

  paths-ignore:
    - '**/.gitignore'
    - '.github/**'
    - 'LICENSE'
    - 'NOTICE'
    - 'src/iceberg/expected.h'

  comment: on-failure
