/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Compiles every public header as C++20, the minimum standard supported for them.
// The header list is generated by ci/scripts/generate_public_headers.py and kept
// up to date by the generate-public-headers pre-commit hook.

#include "iceberg/cpp20_compatibility_internal.h"

#if defined(_MSVC_LANG)
static_assert(_MSVC_LANG == 202002L, "cpp20_compatibility_test must build as C++20");
#else
static_assert(__cplusplus == 202002L, "cpp20_compatibility_test must build as C++20");
#endif

int main() { return 0; }
