name: "Release Docs"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'mkdocs/**'
      - 'src/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material
          sudo apt-get update
          sudo apt-get install -y doxygen

      - name: Build API documentation with Doxygen
        run: |
          cd mkdocs
          mkdir -p docs/api
          doxygen Doxyfile
          echo "Doxygen output created in docs/api/"

      - name: Build docs
        run: |
          cd mkdocs
          mkdocs build --clean
          echo "MkDocs site built in site/"

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4.0.0
        if: github.event_name == 'pull_request'
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

          git checkout --orphan gh-pages-tmp
          git rm --quiet -rf .
          cp -r ./mkdocs/site/* .
          echo "cpp.iceberg.apache.org" > CNAME
          git add --all
          git commit -m "Publish docs from commit ${{ github.sha }}"
          git push -f origin gh-pages-tmp:gh-pages || true
