name: "Release Docs"

on:
  push:
    branches:
      - main
    paths:
      - 'mkdocs/**'
      - 'src/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen
          make install-deps

      - name: Build API documentation with Doxygen
        run: make build-api-docs

      - name: Build docs
        run:
            make build-docs
            mkdir -p /tmp/site
            cp -r ./mkdocs/site/* /tmp/site/

      - name: Deploy to gh-pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

          git checkout --orphan gh-pages-tmp
          git rm --quiet -rf .
          cp -r /tmp/site/* .
          echo "cpp.iceberg.apache.org" > CNAME
          git add --all
          git commit -m "Publish docs from commit ${{ github.sha }}"
          git push -f origin gh-pages-tmp:gh-pages
